"""Add time_taken to Score model

Revision ID: 3d77955b72c2
Revises: 5e39eede4446
Create Date: 2025-07-29 15:49:12.903791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d77955b72c2'
down_revision = '5e39eede4446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('time_taken')

    # ### end Alembic commands ###
